### ISSUE TITLE
DCache exception checking overzealous?

### ISSUE THREAD

**Issue by seldridge** [ucb-bar/rocket#13]
The following change in 7a520740dc4c41694491e6628ff6233b4c76acd8 to nbdcache.scala causes a DCache assertion to trigger for specific program conditions:
```diff
diff --git a/src/main/scala/nbdcache.scala b/src/main/scala/nbdcache.scala
index b7aff71..1a401f0 100644
--- a/src/main/scala/nbdcache.scala
+++ b/src/main/scala/nbdcache.scala
@@ -787,8 +788,8 @@ class HellaCache extends L1HellaCacheModule {
     
   io.cpu.xcpt.ma.ld := s1_read && misaligned
   io.cpu.xcpt.ma.st := s1_write && misaligned
-  io.cpu.xcpt.pf.ld := s1_read && dtlb.io.resp.xcpt_ld
-  io.cpu.xcpt.pf.st := s1_write && dtlb.io.resp.xcpt_st
+  io.cpu.xcpt.pf.ld := !s1_req.phys && s1_read && dtlb.io.resp.xcpt_ld
+  io.cpu.xcpt.pf.st := !s1_req.phys && s1_write && dtlb.io.resp.xcpt_st
 
   assert (!(Reg(next=
     (io.cpu.xcpt.ma.ld || io.cpu.xcpt.ma.st || io.cpu.xcpt.pf.ld || io.cpu.xcpt.pf.st)) &&
```

This starts firing the "DCache exception occurred - cache response not killed" assertion when running a program with an .rodata section > 104B _and_ doing an environment return.

The following program works (hello.rv):
```c
#include <stdio.h>

int main() {

  const char * string_good = "0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456";

  puts(string_good);

  return 0;
}
```
While increasing the .rodata beyond this in the following program (hello-bad.rv) fails:
```c
#include <stdio.h>

int main() {

  const char * string_good = "0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456";
  const char * string_barf = "?";

  puts(string_good);

  return 0;
}
```

When running through the C++ emulator, I then get:
```
$ ./emulator-Top-DefaultCPPConfig pk hello.rv
0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456
$ ./emulator-Top-DefaultCPPConfig pk hello-bad.rv
Assertion failed: DCache exception occurred - cache response not killed
```
If I convert assertions to warnings (build with `--assertWarn`), the program does "work", but there's four instances of the same assertion that fire:
```
$ ./emulator-Top-DefaultCPPConfig pk hello-bad.rv
Assertion failed: DCache exception occurred - cache response not killed
Assertion failed: DCache exception occurred - cache response not killed
Assertion failed: DCache exception occurred - cache response not killed
Assertion failed: DCache exception occurred - cache response not killed
0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456
```
Spike handles both programs fine:
```
$ spike pk hello.rv && spike pk hello-bad.rv
0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456
0123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456789abcdef 123456
```
Similarly, if I remote the `puts`, the program runs fine for both programs (and I checked that the .rodata sections were not optimized away).

After separating the exceptional cases, this is due to a DCache TLB exception due to a load with the TLB triggering its `io.resp.xcpt_ld` because `tlb_hit && !(r_array & tag_cam.io.hits).orR` asserts.

I can't comment on whether or not this is actually wrong or right or on the underlying issue here, but it seems like TLB-originating assertions shouldn't be going off if the request _is_ physical. I'll throw together a pull request under the assumption that my reasoning is right here.

Note, I found this from using HEAD of rocket-chip, so that should probably get a bump bumped once this gets in.

**Comment by ccelio** [comment]
Thanks for the feedback. I think this is something that @zhemao needs to look at, since I suspect your pull request will break the stuff he added for handling memory-mapped IOs (in which a physical address may in fact be "invalid"). 

The meaning behind the assert though is important to consider - an exception from the data cache was discovered and sent to the pipeline, and the cache did NOT receive a kill signal on the next cycle from the pipeline!  The cache is set up such that it will continue trying to perform the invalid memory request, and it's the job of the pipeline to kill it.

So the real questions are:

*  Was the pipeline given an exception that it did not notify the nbdcache of?

* Was the exception actually a valid exception? Or should there be a different control path for this "invalid physical address" information to be handled?


The way the Rocket pipeline works can hide a number of unkilled behaviors (since it re-executes in a number of scenarios), but this behavior can break other processors that depend on nbdcache.

**Comment by seldridge** [comment]
Thanks for the additional information, here, Chris. This clears some things up for me, and yes, I lack the perspective to reliably comment on how this impacts Howard's modifications. 

However, it looks like this was sorted out with the last couple of commits, specifically, 408ba2684fbb5bf46d45d9a3ba2b2c44efbb2d19. I'm no longer tripping assertions on that test program above. I'll close this and back out the pull request.
