### ISSUE TITLE
Streaming data to RoCC

### ISSUE THREAD

**Issue by prashantrar** [ucb-bar/rocket#20]
Is it possible to stream data into the RoCC interface from the L1 cache. Like for example in the " AccumulatorExample" is it possible to load an array of data into the "regfile" that has been defined with just one instruction to trigger the copy.

**Comment by zhemao** [comment]
Yes. The accelerator you write should have a state machine which gets triggered when it receives a command. It should then make sequential requests on the L1 interface and read out the results.

I'm sorry there isn't better documentation on this. We should probably work on getting a document ready for the RISCV workshop.

**Comment by prashantrar** [comment]
Is it possible to post a small sample code with the accumulator example implementing the logic, it would be really helpful

**Comment by seldridge** [comment]
You can also take a look at the SHA-3 accelerator example from rocc-template (https://github.com/ucb-bar/rocc-template/tree/sha3-fix), specifically ctrl.scala which implements a state machine for reading and writing to/from L1. An old version of this was able to get me up to speed pretty quickly. Note, that there are technically two state machines in there that will either send a request and wait for a response _OR_, with the `FastMem` parameter set, send as many requests as it can and deal with sorting them out when they come back (as responses can show up out of order).
