### ISSUE TITLE
[btb] Mixed type mux error

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/rocket#24]
There's a mixed type error in btb.scala, but only shows up for fetchWidth > 1. 

What's the proper idiomatic way to fix this?

````scala
if (fetchWidth == 1) {                                                                                        
  io.resp.bits.mask := UInt(1)                                                                                
} else {                                                                                                                
  io.resp.bits.mask := Mux(io.resp.bits.taken, Cat((UInt(1) << brIdx(io.resp.bits.entry))-1, UInt(1)),        
                                               SInt(-1))                                                      
}                                                                                                             
````

**Comment by zhemao** [comment]
The SInt should be followed by `.toUInt` to convert it to the correct type.

**Comment by ccelio** [comment]
Thanks.  I find the width inference confusing and it's not obvious to me how many bits SInt(-1) is going to be expanded to before it gets converted to a Uint.

**Comment by aswaterman** [comment]
That won't do the right thing here, because the intent was to sign extend.  If the desired width is n, you could do SInt(-1,n).toUInt.

**Comment by ccelio** [comment]
The idea behind the idiom is for it to work without the programmer needing to know the width of the left-hand side (at least, for brevity/readability sake).

Does converting the UInt to an SInt work? Or does that add a bit for the sign?

**Comment by aswaterman** [comment]
If you don't know n, you could instead write ~Mux(s, ~a, UInt(0)) or Mux(s,
a.toSInt, SInt(-1)).toUInt.

**Comment by aswaterman** [comment]
The problem with SInt(-1).toUInt is that the SInt is inferred to have width
1; the UInt is what ultimately gets width-extended. So it's
exactly equivalent to writing UInt(1).

**Comment by ccelio** [comment]
Since `io.resp.bits.mask` is a Bits type, all we need to do is convert the first condition to an SInt?

````
io.resp.bits.mask 
    := Mux(io.resp.bits.taken, 
        Cat((UInt(1) << brIdx(io.resp.bits.entry))-1, UInt(1)).toSInt, 
        SInt(-1))                                                       
````

**Comment by aswaterman** [comment]
Bits isn't a concrete type; mask is either a UInt or an SInt. If you write
Bits() you get a UInt. So you likely do need the second conversion.
