### ISSUE TITLE
Compile error in VCS 

### ISSUE THREAD

**Issue by yyanglattice** [ucb-bar/rocket#49]
hi Rocket experts 
We are trying to build up the rocket environment in your server, some errors shows when we do “make” in vsim: 

“recompiling module rocketTestHarness
All of 85 modules done
make[1]: Entering directory `/lsc/projects/la/yyang4/RISC_V/rocket-chip/vsim/csrc'
cc1: error: unrecognized command line option "-std=c++11"
make[1]: *** [rmapats.o] Error 1
make[1]: Leaving directory `/lsc/projects/la/yyang4/RISC_V/rocket-chip/vsim/csrc' “

looks like the “-std=c++11” options doesn’t compatible our VCS , have you met similar issue before or can you give us some suggestions.  Our GCC version is “4.8.3” and  VCS version is “vcs-mx_vL-2016.06”

**Comment by aswaterman** [comment]
Interesting.  GCC 4.8.3 can handle the -std=c++11 flag.  Perhaps VCS is invoking an older version of GCC?

**Comment by yyanglattice** [comment]
thanks aswaterman, the issue has been resolved, it is a tool install problem

**Comment by aswaterman** [comment]
ok cool
