### ISSUE TITLE
How was performance shown on the README measured?

### ISSUE THREAD

**Issue by cirosantilli** [ucb-bar/rocket#50]
Can you give more details?

Is it a simulation, or a silicon prototype?

Which version of the repository was it based on?

If simulation, which tools were used, and which steps were taken to configure them?

If this design is better than ARM in all aspects and free, why do people still use ARM? :-) (software support, hardware peripheral support?)

**Comment by sorear** [comment]
There have been several silicon prototypes, listed in https://www2.eecs.berkeley.edu/Pubs/TechRpts/2016/EECS-2016-17.pdf .  The table in the README appears to have been copied from https://people.eecs.berkeley.edu/~yunsup/papers/riscv-esscirc2014.pdf .  From the timeline I'm guessing that was "EOS22".

**Comment by ben-k** [comment]
The 2014 ESSCIRC paper was actually EOS14.  (There's a considerable lag between taping out a chip and publishing measured results.)
